name: build-on-pullrequest

on: [pull_request]

jobs:
  smoke-test-pr:
    runs-on: [self-hosted, linux, x64, build3]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          # make sure the checkout can access the parent commit, too
          fetch-depth: 2
          # checkout pull request HEAD commit instead of merge commit
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 'npm ci'
        shell: bash
        run: npm ci

      - name: 'Check TypeScript'
        shell: bash
        run: npm run tsc-once

      - name: 'Check lint'
        shell: bash
        run: npm run lint
